matrix:
    include:
      -language: php
        php:
          - '5.4'
          - '5.5'
          - '5.6'
          - '7.0'
        services:
          -mysql
        #command to run the test
        after_success: coveralls
