matrix:
    include:
      -language: php
        php:
          - '5.4'
          - '5.5'
          - '5.6'
          - '7.0'
        services:
          -mysql
        #command to run the test
        script:
          - "phpunit --testsuite=unit --coverage-clover coverage.xml"
        after_script:
          - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
          - php coveralls.phar --verbose
        after_success: coveralls
