matrix:
  include:
  - language: php
  php:
    - 5.4
    - 5.5
    - 5.6
  
  services:
    - mysql
  before_script:
    - travis_retry composer self-update
    - composer install
    - mysql -u root -e "CREATE DATABASE piykvshj_database1;"
    - mysql -u root -e "CREATE user 'piykvshj'@'localhost' IDENTIFIED BY 'Differ123*cpanel';"
    - mysql -u root -e "GRANT ALL ON piykvshj_database1.* TO 'piykvshj'@'localhost';"
  script:
    - "phpunit --testsuite=unit --coverage-clover coverage.xml"
  after_script:
    - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
    - php coveralls.phar --verbose
  after_success:
    - coveralls
